# Generated by Django 5.0 on 2023-12-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodeA", models.IntegerField()),
                ("CodeB", models.IntegerField()),
                ("date", models.IntegerField()),
                ("sell", models.FloatField()),
                ("buy", models.FloatField()),
                ("cross", models.FloatField()),
            ],
        ),
    ]
