# Generated by Django 5.0 on 2023-12-27 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simple_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="currency",
            name="cross",
        ),
    ]
