# Generated by Django 5.0 on 2023-12-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simple_app", "0002_remove_currency_cross"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="date",
            field=models.CharField(max_length=10),
        ),
    ]
