# Generated by Django 5.0 on 2023-12-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simple_app", "0003_alter_currency_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="CodeA",
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name="currency",
            name="CodeB",
            field=models.CharField(max_length=3),
        ),
    ]
