# Generated by Django 5.0 on 2023-12-28 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simple_app", "0005_alter_currency_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="currency",
            old_name="CodeA",
            new_name="code_a",
        ),
        migrations.RenameField(
            model_name="currency",
            old_name="CodeB",
            new_name="code_b",
        ),
    ]
